### ISSUE TITLE
Failed to activate the mechanical-keyboard package

### ISSUE THREAD

**Issue by muhasturk** [remanc/mechanical-keyboard#8]
**Atom Version**: 0.204.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [mechanical-keyboard](https://github.com/remanc/mechanical-keyboard) package, v0.1.0
### Stack Trace

Failed to activate the mechanical-keyboard package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/muhasturk/.atom/packages/mechanical-keyboard/lib/mechanical-keyboard.coffee:10:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "seti-ui",
      "bittersweet-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
bittersweet-syntax, v0.1.1
color-picker, v2.0.2
emmet, v2.3.10
linter, v0.12.6
mechanical-keyboard, v0.1.0
minimap, v4.9.2
seti-ui, v0.7.1
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by zerojuan** [comment]
Hi @muhasturk, see #5
